// Code generated by "stringer -type=CloseReason -output close_reason_string.go"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CloseNormal-0]
	_ = x[CloseByPeer-1]
	_ = x[CloseUnknownError-2]
	_ = x[CloseWithWillMessage-4]
	_ = x[CloseUnspecifiedReason-128]
	_ = x[CloseMalformedPacket-129]
	_ = x[CloseWrongProtocol-130]
	_ = x[CloseNotImplement-131]
	_ = x[CloseNotAuthorized-135]
	_ = x[CloseBusy-137]
	_ = x[CloseClosing-139]
	_ = x[CloseKeepAliveTimeout-141]
	_ = x[CloseDupSession-143]
	_ = x[CloseTopicFilterInvalid-143]
	_ = x[CloseTopicNameInvalid-144]
	_ = x[CloseBufferOverflow-147]
	_ = x[CloseTopicAliasInvalid-148]
	_ = x[ClosePacketTooLong-149]
	_ = x[ClosePacketRateTooFast-150]
	_ = x[CloseQuoteOverflow-151]
	_ = x[CloseAdministrativeOperate-152]
	_ = x[ClosePayloadFormatInvalid-153]
	_ = x[CloseUnsupportedRetain-154]
	_ = x[CloseUnsupportedQoS-155]
	_ = x[CloseUseOtherServer-156]
	_ = x[CloseServerMovedPermanent-157]
	_ = x[CloseUnsupportedSharedSubscription-158]
	_ = x[CloseConnectionMadeTooFreq-159]
	_ = x[CloseConnectionTimeout-160]
	_ = x[CloseUnsupportedSubscriptionId-161]
	_ = x[CloseUnsupportedWildcardSubscription-162]
}

const (
	_CloseReason_name_0 = "CloseNormalCloseByPeerCloseUnknownError"
	_CloseReason_name_1 = "CloseWithWillMessage"
	_CloseReason_name_2 = "CloseUnspecifiedReasonCloseMalformedPacketCloseWrongProtocolCloseNotImplement"
	_CloseReason_name_3 = "CloseNotAuthorized"
	_CloseReason_name_4 = "CloseBusy"
	_CloseReason_name_5 = "CloseClosing"
	_CloseReason_name_6 = "CloseKeepAliveTimeout"
	_CloseReason_name_7 = "CloseDupSessionCloseTopicNameInvalid"
	_CloseReason_name_8 = "CloseBufferOverflowCloseTopicAliasInvalidClosePacketTooLongClosePacketRateTooFastCloseQuoteOverflowCloseAdministrativeOperateClosePayloadFormatInvalidCloseUnsupportedRetainCloseUnsupportedQoSCloseUseOtherServerCloseServerMovedPermanentCloseUnsupportedSharedSubscriptionCloseConnectionMadeTooFreqCloseConnectionTimeoutCloseUnsupportedSubscriptionIdCloseUnsupportedWildcardSubscription"
)

var (
	_CloseReason_index_0 = [...]uint8{0, 11, 22, 39}
	_CloseReason_index_2 = [...]uint8{0, 22, 42, 60, 77}
	_CloseReason_index_7 = [...]uint8{0, 15, 36}
	_CloseReason_index_8 = [...]uint16{0, 19, 41, 59, 81, 99, 125, 150, 172, 191, 210, 235, 269, 295, 317, 347, 383}
)

func (i CloseReason) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _CloseReason_name_0[_CloseReason_index_0[i]:_CloseReason_index_0[i+1]]
	case i == 4:
		return _CloseReason_name_1
	case 128 <= i && i <= 131:
		i -= 128
		return _CloseReason_name_2[_CloseReason_index_2[i]:_CloseReason_index_2[i+1]]
	case i == 135:
		return _CloseReason_name_3
	case i == 137:
		return _CloseReason_name_4
	case i == 139:
		return _CloseReason_name_5
	case i == 141:
		return _CloseReason_name_6
	case 143 <= i && i <= 144:
		i -= 143
		return _CloseReason_name_7[_CloseReason_index_7[i]:_CloseReason_index_7[i+1]]
	case 147 <= i && i <= 162:
		i -= 147
		return _CloseReason_name_8[_CloseReason_index_8[i]:_CloseReason_index_8[i+1]]
	default:
		return "CloseReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
